version: '3.8'

services:
  revendaja:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=revendaja 

  toxiproxy:
    image: shopify/toxiproxy
    ports:
      - "8474:8474"   # API do Toxiproxy
      - "8666:8666"   # Porta para proxy do banco